// Code generated by MockGen. DO NOT EDIT.
// Source: handlers.go

// Package mock_delivery is a generated GoMock package.
package mock_delivery

import mock_service "doodocsbackendchallenge/internal/service/mocks"
type MockHandler struct {
	mockServices *mock_service.MockService
	log *slog.Logger 
} 
type HandlerFactory func(mockservice mock_service.MockService, log *slog.Logger) *MockHandler

var NewHandler HandlerFactory = func(mockservices *mock_service.MockService, log *slog.Logger) *MockHandler {
    return &MockHandler{
        mockServices: mockservices,
        log:      log,
    }
}